import AuthContext from "@/contexts/AuthContext/AuthContext";
import "./globals.css";
import React from "react";
import Header from "./components/layout/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-satoshi">
        <AuthContext>
          <section>
            <Header />
            <div className="flex mx-auto overflow-hidden">{children}</div>
          </section>
          <div id="modal-root" />
        </AuthContext>
      </body>
    </html>
  );
}
